subdomain: matrix
domain: striker.red

system_packages:
  - libtiff-devel
  - libjpeg-devel
  - libzip-devel
  - freetype-devel
  - lcms2
  - libwebp-devel
  - tcl-devel
  - tk-devel
  - redhat-rpm-config
  - python36
  #- virtualenv
  - libffi-devel
  - openssl-devel

running_user: joey

home: "/home/{{ running_user }}"
synapse_path: "{{ home }}/synapse"
venv_name: "venv_synapse"
virtualenv_path: "{{ home }}/.pyenv/versions/{{ venv_name }}"
pyenv_cmd: "{{ home }}/.pyenv/bin/pyenv"

#pip_packages:
#  - pip 
#  #- virtualenv
#  - six 
#  - packaging
#  - appdirs
#  - setuptools
#  - matrix-synapse

pip_packages: "pip six packaging appdirs setuptools matrix-synapse"
