domain: striker.red

system_packages:
  - libtiff-devel
  - libjpeg-devel
  - libzip-devel
  - freetype-devel
  - lcms2
  - libwebp-devel
  - tcl-devel
  - tk-devel
  - redhat-rpm-config
  - python36
  #- virtualenv
  - libffi-devel
  - openssl-devel

running_user: joey

virtualenv_path: "/home/{{ running_user }}/synapse"

pip_packages:
  - pip 
  #- virtualenv
  - six 
  - packaging
  - appdirs
  - setuptools
  - matrix-synapse
